{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "ABCOpt.C",
      "version": "0.3.2",
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/ucfilho/Codigos_Teste/blob/master/ABCOpt_C.C\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "jP6YmmsGo_ba",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "/* ABC algorithm coded using C programming language */\n",
        "\n",
        "/* Artificial Bee Colony (ABC) is one of the most recently defined algorithms by Dervis Karaboga in 2005, \n",
        "motivated by the intelligent behavior of honey bees. */\n",
        "\n",
        "/* Referance Papers*/\n",
        "\n",
        "/*D. Karaboga, AN IDEA BASED ON HONEY BEE SWARM FOR NUMERICAL OPTIMIZATION,TECHNICAL REPORT-TR06, Erciyes University, Engineering Faculty, Computer Engineering Department 2005.*/\n",
        "\n",
        "/*D. Karaboga, B. Basturk, A powerful and Efficient Algorithm for Numerical Function Optimization: Artificial Bee Colony (ABC) Algorithm, Journal of Global Optimization, Volume:39, Issue:3,pp:459-171, November 2007,ISSN:0925-5001 , doi: 10.1007/s10898-007-9149-x */\n",
        "\n",
        "/*D. Karaboga, B. Basturk, On The Performance Of Artificial Bee Colony (ABC) Algorithm, Applied Soft Computing,Volume 8, Issue 1, January 2008, Pages 687-697. */\n",
        "\n",
        "/*D. Karaboga, B. Akay, A Comparative Study of Artificial Bee Colony Algorithm,  Applied Mathematics and Computation, 214, 108-132, 2009. */\n",
        "\n",
        "/*Copyright © 2009 Erciyes University, Intelligent Systems Research Group, The Dept. of Computer Engineering*/\n",
        "\n",
        "/*Contact:\n",
        "Dervis Karaboga (karaboga@erciyes.edu.tr )\n",
        "Bahriye Basturk Akay (bahriye@erciyes.edu.tr)\n",
        "*/\n",
        "\n",
        "\n",
        "#include <stdio.h>\n",
        "#include <stdlib.h>\n",
        "#include <math.h>\n",
        "#include <conio.h>\n",
        "#include <time.h>\n",
        "\n",
        "\n",
        "/* Control Parameters of ABC algorithm*/\n",
        "#define NP 40 /* The number of colony size (employed bees+onlooker bees)*/\n",
        "#define FoodNumber NP/2 /*The number of food sources equals the half of the colony size*/\n",
        "#define limit 100  /*A food source which could not be improved through \"limit\" trials is abandoned by its employed bee*/\n",
        "#define maxCycle 3000 /*The number of cycles for foraging {a stopping criteria}*/\n",
        "\n",
        "/* Problem specific variables*/\n",
        "#define D 50 /*The number of parameters of the problem to be optimized*/\n",
        "#define lb -5.12 /*lower bound of the parameters. */\n",
        "#define ub 5.12 /*upper bound of the parameters. lb and ub can be defined as arrays for the problems of which parameters have different bounds*/\n",
        "\n",
        "\n",
        "#define runtime 30  /*Algorithm can be run many times in order to see its robustness*/\n",
        "\n",
        "\n",
        "double Foods[FoodNumber][D]; /*Foods is the population of food sources. Each row of Foods matrix is a vector holding D parameters to be optimized. The number of rows of Foods matrix equals to the FoodNumber*/\n",
        "double f[FoodNumber];  /*f is a vector holding objective function values associated with food sources */\n",
        "double fitness[FoodNumber]; /*fitness is a vector holding fitness (quality) values associated with food sources*/\n",
        "double trial[FoodNumber]; /*trial is a vector holding trial numbers through which solutions can not be improved*/\n",
        "double prob[FoodNumber]; /*prob is a vector holding probabilities of food sources (solutions) to be chosen*/\n",
        "double solution [D]; /*New solution (neighbour) produced by v_{ij}=x_{ij}+\\phi_{ij}*(x_{kj}-x_{ij}) j is a randomly chosen parameter and k is a randomlu chosen solution different from i*/\n",
        "double ObjValSol; /*Objective function value of new solution*/\n",
        "double FitnessSol; /*Fitness value of new solution*/\n",
        "int neighbour, param2change; /*param2change corrresponds to j, neighbour corresponds to k in equation v_{ij}=x_{ij}+\\phi_{ij}*(x_{kj}-x_{ij})*/\n",
        "double GlobalMin; /*Optimum solution obtained by ABC algorithm*/\n",
        "double GlobalParams[D]; /*Parameters of the optimum solution*/\n",
        "double GlobalMins[runtime]; /*GlobalMins holds the GlobalMin of each run in multiple runs*/\n",
        "double r; /*a random number in the range [0,1)*/\n",
        "\n",
        "/*a function pointer returning double and taking a D-dimensional array as argument */\n",
        "/*If your function takes additional arguments then change function pointer definition and lines calling \"...=function(solution);\" in the code*/\n",
        "typedef double (*FunctionCallback)(double sol[D]); \n",
        "\n",
        "/*benchmark functions */\n",
        "double sphere(double sol[D]);\n",
        "double Rosenbrock(double sol[D]);\n",
        "double Griewank(double sol[D]);\n",
        "double Rastrigin(double sol[D]);\n",
        "\n",
        "/*Write your own objective function name instead of sphere*/\n",
        "FunctionCallback function = &Rastrigin;\n",
        "\n",
        "/*Fitness function*/\n",
        "double CalculateFitness(double fun)\n",
        " {\n",
        "\t double result=0;\n",
        "\t if(fun>=0)\n",
        "\t {\n",
        "\t\t result=1/(fun+1);\n",
        "\t }\n",
        "\t else\n",
        "\t {\n",
        "\t\t result=1+fabs(fun);\n",
        "\t }\n",
        "\t return result;\n",
        " }\n",
        "\n",
        "/*The best food source is memorized*/\n",
        "void MemorizeBestSource()\n",
        "{\n",
        "   int i,j;\n",
        "    \n",
        "\tfor(i=0;i<FoodNumber;i++)\n",
        "\t{\n",
        "\tif (f[i]<GlobalMin)\n",
        "\t\t{\n",
        "        GlobalMin=f[i];\n",
        "        for(j=0;j<D;j++)\n",
        "           GlobalParams[j]=Foods[i][j];\n",
        "        }\n",
        "\t}\n",
        " }\n",
        "\n",
        "/*Variables are initialized in the range [lb,ub]. If each parameter has different range, use arrays lb[j], ub[j] instead of lb and ub */\n",
        "/* Counters of food sources are also initialized in this function*/\n",
        "void init(int index)\n",
        "{\n",
        "   int j;\n",
        "   for (j=0;j<D;j++)\n",
        "\t\t{\n",
        "        r = (   (double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        Foods[index][j]=r*(ub-lb)+lb;\n",
        "\t\tsolution[j]=Foods[index][j];\n",
        "\t\t}\n",
        "\tf[index]=function(solution);\n",
        "\tfitness[index]=CalculateFitness(f[index]);\n",
        "\ttrial[index]=0;\n",
        "}\n",
        "\n",
        "/*All food sources are initialized */\n",
        "void initial()\n",
        "{\n",
        "\tint i;\n",
        "\tfor(i=0;i<FoodNumber;i++)\n",
        "\t{\n",
        "\tinit(i);\n",
        "\t}\n",
        "\tGlobalMin=f[0];\n",
        "    for(i=0;i<D;i++)\n",
        "    GlobalParams[i]=Foods[0][i];\n",
        "\n",
        "\n",
        "}\n",
        "\n",
        "void SendEmployedBees()\n",
        "{\n",
        "  int i,j;\n",
        "  /*Employed Bee Phase*/\n",
        "   for (i=0;i<FoodNumber;i++)\n",
        "        {\n",
        "        /*The parameter to be changed is determined randomly*/\n",
        "        r = ((double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        param2change=(int)(r*D);\n",
        "        \n",
        "        /*A randomly chosen solution is used in producing a mutant solution of the solution i*/\n",
        "        r = (   (double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        neighbour=(int)(r*FoodNumber);\n",
        "\n",
        "        /*Randomly selected solution must be different from the solution i*/        \n",
        "        while(neighbour==i)\n",
        "        {\n",
        "        r = (   (double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        neighbour=(int)(r*FoodNumber);\n",
        "        }\n",
        "        for(j=0;j<D;j++)\n",
        "        solution[j]=Foods[i][j];\n",
        "\n",
        "        /*v_{ij}=x_{ij}+\\phi_{ij}*(x_{kj}-x_{ij}) */\n",
        "        r = (   (double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        solution[param2change]=Foods[i][param2change]+(Foods[i][param2change]-Foods[neighbour][param2change])*(r-0.5)*2;\n",
        "\n",
        "        /*if generated parameter value is out of boundaries, it is shifted onto the boundaries*/\n",
        "        if (solution[param2change]<lb)\n",
        "           solution[param2change]=lb;\n",
        "        if (solution[param2change]>ub)\n",
        "           solution[param2change]=ub;\n",
        "        ObjValSol=function(solution);\n",
        "        FitnessSol=CalculateFitness(ObjValSol);\n",
        "        \n",
        "        /*a greedy selection is applied between the current solution i and its mutant*/\n",
        "        if (FitnessSol>fitness[i])\n",
        "        {\n",
        "        /*If the mutant solution is better than the current solution i, replace the solution with the mutant and reset the trial counter of solution i*/\n",
        "        trial[i]=0;\n",
        "        for(j=0;j<D;j++)\n",
        "        Foods[i][j]=solution[j];\n",
        "        f[i]=ObjValSol;\n",
        "        fitness[i]=FitnessSol;\n",
        "        }\n",
        "        else\n",
        "        {   /*if the solution i can not be improved, increase its trial counter*/\n",
        "            trial[i]=trial[i]+1;\n",
        "        }\n",
        "\n",
        "\n",
        "        }\n",
        "\n",
        "        /*end of employed bee phase*/\n",
        "\n",
        "}\n",
        "\n",
        "/* A food source is chosen with the probability which is proportioal to its quality*/\n",
        "/*Different schemes can be used to calculate the probability values*/\n",
        "/*For example prob(i)=fitness(i)/sum(fitness)*/\n",
        "/*or in a way used in the metot below prob(i)=a*fitness(i)/max(fitness)+b*/\n",
        "/*probability values are calculated by using fitness values and normalized by dividing maximum fitness value*/\n",
        "void CalculateProbabilities()\n",
        "{\n",
        "     int i;\n",
        "     double maxfit;\n",
        "     maxfit=fitness[0];\n",
        "  for (i=1;i<FoodNumber;i++)\n",
        "        {\n",
        "           if (fitness[i]>maxfit)\n",
        "           maxfit=fitness[i];\n",
        "        }\n",
        "\n",
        " for (i=0;i<FoodNumber;i++)\n",
        "        {\n",
        "         prob[i]=(0.9*(fitness[i]/maxfit))+0.1;\n",
        "        }\n",
        "\n",
        "}\n",
        "\n",
        "void SendOnlookerBees()\n",
        "{\n",
        "\n",
        "  int i,j,t;\n",
        "  i=0;\n",
        "  t=0;\n",
        "  /*onlooker Bee Phase*/\n",
        "  while(t<FoodNumber)\n",
        "        {\n",
        "\n",
        "        r = (   (double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        if(r<prob[i]) /*choose a food source depending on its probability to be chosen*/\n",
        "        {        \n",
        "        t++;\n",
        "        \n",
        "        /*The parameter to be changed is determined randomly*/\n",
        "        r = ((double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        param2change=(int)(r*D);\n",
        "        \n",
        "        /*A randomly chosen solution is used in producing a mutant solution of the solution i*/\n",
        "        r = (   (double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        neighbour=(int)(r*FoodNumber);\n",
        "\n",
        "        /*Randomly selected solution must be different from the solution i*/        \n",
        "        while(neighbour==i)\n",
        "        {\n",
        "        r = (   (double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        neighbour=(int)(r*FoodNumber);\n",
        "        }\n",
        "        for(j=0;j<D;j++)\n",
        "        solution[j]=Foods[i][j];\n",
        "\n",
        "        /*v_{ij}=x_{ij}+\\phi_{ij}*(x_{kj}-x_{ij}) */\n",
        "        r = (   (double)rand() / ((double)(RAND_MAX)+(double)(1)) );\n",
        "        solution[param2change]=Foods[i][param2change]+(Foods[i][param2change]-Foods[neighbour][param2change])*(r-0.5)*2;\n",
        "\n",
        "        /*if generated parameter value is out of boundaries, it is shifted onto the boundaries*/\n",
        "        if (solution[param2change]<lb)\n",
        "           solution[param2change]=lb;\n",
        "        if (solution[param2change]>ub)\n",
        "           solution[param2change]=ub;\n",
        "        ObjValSol=function(solution);\n",
        "        FitnessSol=CalculateFitness(ObjValSol);\n",
        "        \n",
        "        /*a greedy selection is applied between the current solution i and its mutant*/\n",
        "        if (FitnessSol>fitness[i])\n",
        "        {\n",
        "        /*If the mutant solution is better than the current solution i, replace the solution with the mutant and reset the trial counter of solution i*/\n",
        "        trial[i]=0;\n",
        "        for(j=0;j<D;j++)\n",
        "        Foods[i][j]=solution[j];\n",
        "        f[i]=ObjValSol;\n",
        "        fitness[i]=FitnessSol;\n",
        "        }\n",
        "        else\n",
        "        {   /*if the solution i can not be improved, increase its trial counter*/\n",
        "            trial[i]=trial[i]+1;\n",
        "        }\n",
        "        } /*if */\n",
        "        i++;\n",
        "        if (i==FoodNumber)\n",
        "        i=0;\n",
        "        }/*while*/\n",
        "\n",
        "        /*end of onlooker bee phase     */\n",
        "}\n",
        "\n",
        "/*determine the food sources whose trial counter exceeds the \"limit\" value. In Basic ABC, only one scout is allowed to occur in each cycle*/\n",
        "void SendScoutBees()\n",
        "{\n",
        "int maxtrialindex,i;\n",
        "maxtrialindex=0;\n",
        "for (i=1;i<FoodNumber;i++)\n",
        "        {\n",
        "         if (trial[i]>trial[maxtrialindex])\n",
        "         maxtrialindex=i;\n",
        "        }\n",
        "if(trial[maxtrialindex]>=limit)\n",
        "{\n",
        "\tinit(maxtrialindex);\n",
        "}\n",
        "}\n",
        "\n",
        "\n",
        "/*Main program of the ABC algorithm*/\n",
        "int main()\n",
        "{\n",
        "int iter,run,j;\n",
        "double mean;\n",
        "mean=0;\n",
        "srand(time(NULL));\n",
        "\n",
        "for(run=0;run<runtime;run++)\n",
        "{\n",
        "\n",
        "initial();\n",
        "MemorizeBestSource();\n",
        "for (iter=0;iter<maxCycle;iter++)\n",
        "    {\n",
        "    SendEmployedBees();\n",
        "    CalculateProbabilities();\n",
        "    SendOnlookerBees();\n",
        "    MemorizeBestSource();\n",
        "    SendScoutBees();\n",
        "    }\n",
        "for(j=0;j<D;j++)\n",
        "\t\t{\n",
        "\t\t\tprintf(\"GlobalParam[%d]: %f\\n\",j+1,GlobalParams[j]);\n",
        "\t\t}\n",
        "printf(\"%d. run: %e \\n\",run+1,GlobalMin);\n",
        "GlobalMins[run]=GlobalMin;\n",
        "mean=mean+GlobalMin;\n",
        "}\n",
        "mean=mean/runtime;\n",
        "printf(\"Means of %d runs: %e\\n\",runtime,mean);\n",
        "getch();\n",
        "}\n",
        "\n",
        "\n",
        "double sphere(double sol[D])\n",
        "{\n",
        "int j;\n",
        "double top=0;\n",
        "for(j=0;j<D;j++)\n",
        "{\n",
        "top=top+sol[j]*sol[j];\n",
        "}\n",
        "return top;\n",
        "}\n",
        "\n",
        "double Rosenbrock(double sol[D])\n",
        "{\n",
        "int j;\n",
        "double top=0;\n",
        "for(j=0;j<D-1;j++)\n",
        "{\n",
        "top=top+100*pow((sol[j+1]-pow((sol[j]),(double)2)),(double)2)+pow((sol[j]-1),(double)2);\n",
        "}\n",
        "return top;\n",
        "}\n",
        "\n",
        " double Griewank(double sol[D])\n",
        " {\n",
        "\t int j;\n",
        "\t double top1,top2,top;\n",
        "\t top=0;\n",
        "\t top1=0;\n",
        "\t top2=1;\n",
        "\t for(j=0;j<D;j++)\n",
        "\t {\n",
        "\t\t top1=top1+pow((sol[j]),(double)2);\n",
        "\t\t top2=top2*cos((((sol[j])/sqrt((double)(j+1)))*M_PI)/180);\n",
        "\n",
        "\t }\t\n",
        "\t top=(1/(double)4000)*top1-top2+1;\n",
        "\t return top;\n",
        " }\n",
        "\n",
        " double Rastrigin(double sol[D])\n",
        " {\n",
        "\t int j;\n",
        "\t double top=0;\n",
        "\n",
        "\t for(j=0;j<D;j++)\n",
        "\t {\n",
        "\t\t top=top+(pow(sol[j],(double)2)-10*cos(2*M_PI*sol[j])+10);\n",
        "\t }\n",
        "\t return top;\n",
        " }"
      ],
      "execution_count": 0,
      "outputs": []
    }
  ]
}